name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: "go.mod"
          cache: false
      - name: Install dependencies
        run: make lint-install
      - name: Lint
        run: make lint
      - name: Test
        run: make test
